version: '3.6'
services:
  kls-user:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
